### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by slumnitz** [UBC-MDS/DSCI-532_gr202_dashboard#40]
Overall well done!

Here are a couple things you could improve on for full marks:
-Team work contract could be more specific: What are tasks? Who takes which jobs? When are they due?
- Be aware, you are showing a spatial distribution of crime using Choropleths, crime density would be eg. crime-count/area in sqm.

Generally:
Keep the good work up! Make sure to divide work and commits equally, keep your commit messages informative (try answer: What exactly did you update/ change?), communicate via issues, or even check out the GitHub project functionality!

**Comment by miketianchen** [comment]
https://github.com/UBC-MDS/DSCI-532_gr202_dashboard/blob/181adeae44fd4af3295ca990d85b0725ade444ab/Proposal.md
