### ISSUE TITLE
Lab 3 Peer Review

### ISSUE THREAD

**Issue by tejasph** [UBC-MDS/DSCI-532_gr202_dashboard#50]
- map gradient sometimes has 1 number only, when only neighborhood is selected (this confused us initially) --> can maybe reformat if 1 neighborhood is selected.
- lots of space on the left, wonder if it could be utilized better
- diagrams are delayed when updating the selections --> perhaps brainstorms ways to optimize
- Menu text could be simplified. 

Really clean looking dashboard. I liked the text in the menu panel that helps inform the user about how the dashboard works. Great job overall!

**Comment by zanderhinton** [comment]
Moved to summary issue.
