### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by merveshin** [UBC-MDS/DSCI-532_gr202_dashboard#51]
for the second graph, it can be a little bit wider. 
You can add more usage scenarios at the beginning part.
You can add another line on the line chart to show the difference between crime types.
You can add a link data source.
You may add a Github link for the group repo.
You can shift the last graph a little bit left to put the graphs on the same line.
You can remove the last months to get rid of the weird ends.

**Comment by zanderhinton** [comment]
Moved to summary issue.
