### ISSUE TITLE
Peer Review from Miro & Jasmine

### ISSUE THREAD

**Issue by mirohu** [UBC-MDS/DSCI-532_gr202_dashboard#52]
The dashboard is very impressive. Well done guys! 

Here are something that I would improve:
- I would distinguish the crime trend graph with other graphs since it's not changing with the 'month filter'
- I would try to optimize the loading time 
- I would be more specific with what the  'month filter' does - for example, if I filter year '2015' to '2017', month 'Jan' to 'Dec', it's a bit confusing to me that if I am selecting 'Jan to Dec for 2015 to 2017' or '2015 Jan to 2017 Dec'. It would be very helpful to specify it somewhere.
- I would specify the title of the 'crime count graph' as it's hard to figure out that it's showing the top 10.

**Comment by zanderhinton** [comment]
Moved to summary issue.
