### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by bbaillie** [UBC-MDS/DSCI-532_gr202_dashboard#53]
- Lots of options for filtering data
- date axis for crime trend plot is very confusing, perhaps use years as the tick marks along the x-axis to make it easier to understand the date range, months and days aren't necessary to have on the axis but are nice to have on the tooltip
- on that same plot it would be nice if you could get the name of the month to show up instead of the number on the tooltip
- super big dataset causes app to have trouble rendering on Heroku
- good explanation on usage in the intro
- crime trend figure could benefit from being wider and having larger dots for interaction
- perhaps have only the neighbourhoods that are selected show up (this feature was already implemented and you removed it but we think it should go back)
- include lines for neighbourhoods in the full figure, even if they don't data (maybe use like greyed out lines to show no data)
- side bar with filtering information could maybe handle being a little larger for more ease with interaction, and also larger font

we didn't get to interact with your app fully (we assume) because the size of the data and the number of features didn't render on Heroku. The app also crashed sometimes when we were trying to open it.

**Comment by zanderhinton** [comment]
Moved to summary issue.
